# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.13']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        export GITHUB_ACTIONS=true
        make install
    - name: Create env file
      run: |
        touch .env
        echo RELOAD=true >> .env

        echo DB_DRIVERNAME="mysql" >> .env
        echo DB_USERNAME="root" >> .env
        echo DB_PASSWORD="password" >> .env
        echo DB_HOST="localhost" >> .env
        echo DB_PORT=3306 >> .env
        echo DB_DATABASE="database" >> .env

        echo SENDGRID_API_KEY="key" >> .env
        echo SENDGRID_EMAIL="email" >> .env

        echo SECRET_KEY="key" >> .env
        echo ALGORITHM="HS256" >> .env
        echo ACCESS_TOKEN_EXPIRE_MINUTES=30 >> .env
        cat .env
    - name: Test Application
      run: |
        make test